/**
 * fix_rls_policies.js
 * 
 * Applies permissive RLS policies on all tables the mobile app needs to
 * READ and WRITE via the anon key (no auth session).
 * 
 * Run once with: node scripts/fix_rls_policies.js
 */

const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = 'https://lckwxhtdjrmzhffulwse.supabase.co';
// Service role key bypasses RLS — needed to apply the policies themselves
const SERVICE_ROLE_KEY = 'sb_secret_EYfqaW5QW0LpC-wI8G2t-mD7-S7oBq6l_W3UoX5_';

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

// Tables the mobile app needs full CRUD access to (via anon key, no auth)
const TABLES = [
    'patients',
    'baumann_responses',
    'skin_analyses',
    'pharmacy_products',
    'recommendations',
];

async function execSQL(sql, description) {
    console.log(`\n▶  ${description}`);
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/exec_sql`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'apikey': SERVICE_ROLE_KEY,
            'Authorization': `Bearer ${SERVICE_ROLE_KEY}`,
        },
        body: JSON.stringify({ sql }),
    });

    // If we don't have exec_sql, fall back to the pg_admin approach
    if (!res.ok) {
        const txt = await res.text();
        console.warn(`  exec_sql RPC not available (${res.status}): ${txt.slice(0, 200)}`);
        return false;
    }
    const data = await res.json();
    console.log('  ✓ Done:', JSON.stringify(data).slice(0, 120));
    return true;
}

async function applyRLSViaDirect(sql, description) {
    console.log(`\n▶  ${description}`);
    // Use the Management API SQL endpoint
    const projectRef = 'lckwxhtdjrmzhffulwse';
    // Note: This requires a Supabase personal access token, not service role key.
    // We'll instead build the SQL and log it for manual application.
    console.log('  SQL to apply:\n', sql);
}

// ─── Build complete SQL migration ──────────────────────────────────────────

function buildRLSSQL(tables) {
    const lines = [
        '-- BeSkinPro Mobile: Allow anon full CRUD on all app tables',
        '-- Generated by fix_rls_policies.js',
        '',
    ];

    for (const table of tables) {
        lines.push(`-- ── ${table} ──────────────────────────────────────`);
        // Ensure RLS is enabled
        lines.push(`ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY;`);
        lines.push('');

        // Drop old conflicting policies if they exist (ignore errors)
        const policies = [
            `Allow anon select on ${table}`,
            `Allow anon insert on ${table}`,
            `Allow anon update on ${table}`,
            `Allow anon delete on ${table}`,
            `anon_select_${table}`,
            `anon_insert_${table}`,
            `anon_update_${table}`,
            `anon_delete_${table}`,
        ];
        for (const p of policies) {
            lines.push(`DROP POLICY IF EXISTS "${p}" ON public.${table};`);
        }

        // Create open policies for anon role
        lines.push(`CREATE POLICY "anon_select_${table}" ON public.${table} FOR SELECT TO anon USING (true);`);
        lines.push(`CREATE POLICY "anon_insert_${table}" ON public.${table} FOR INSERT TO anon WITH CHECK (true);`);
        lines.push(`CREATE POLICY "anon_update_${table}" ON public.${table} FOR UPDATE TO anon USING (true) WITH CHECK (true);`);
        lines.push(`CREATE POLICY "anon_delete_${table}" ON public.${table} FOR DELETE TO anon USING (true);`);
        lines.push('');
    }

    // Also grant usage+CRUD on all tables at the PostgreSQL level
    lines.push('-- Grant table-level permissions to anon role');
    lines.push(`GRANT USAGE ON SCHEMA public TO anon;`);
    for (const table of tables) {
        lines.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON public.${table} TO anon;`);
    }
    lines.push('');
    lines.push('-- Confirm');
    lines.push(`SELECT tablename, rowsecurity FROM pg_tables WHERE schemaname = 'public' AND tablename IN (${tables.map(t => `'${t}'`).join(', ')});`);

    return lines.join('\n');
}

async function main() {
    const sql = buildRLSSQL(TABLES);

    console.log('='.repeat(60));
    console.log('BeSkinPro Mobile — RLS Policy Fix');
    console.log('='.repeat(60));
    console.log('\nTables to fix:', TABLES.join(', '));
    console.log('\n' + '─'.repeat(60));
    console.log('SQL Migration to apply in Supabase SQL Editor:');
    console.log('─'.repeat(60));
    console.log(sql);
    console.log('─'.repeat(60));

    // Try applying via direct fetch to Supabase REST (needs exec_sql function)
    // If that fails, the SQL is printed above for manual application
    console.log('\nAttempting to apply via Supabase API...');

    const url = `${SUPABASE_URL}/rest/v1/rpc/exec_sql`;
    try {
        const res = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'apikey': SERVICE_ROLE_KEY,
                'Authorization': `Bearer ${SERVICE_ROLE_KEY}`,
            },
            body: JSON.stringify({ sql }),
        });
        const body = await res.text();
        if (res.ok) {
            console.log('\n✅ Policies applied successfully via API!');
        } else {
            console.log(`\n⚠️  API exec_sql not available (status ${res.status}).`);
            console.log('Please copy the SQL above and paste it into:');
            console.log('  https://supabase.com/dashboard/project/lckwxhtdjrmzhffulwse/sql/new');
        }
    } catch (e) {
        console.log('\n⚠️  Could not reach API:', e.message);
        console.log('Please copy the SQL above and paste it into:');
        console.log('  https://supabase.com/dashboard/project/lckwxhtdjrmzhffulwse/sql/new');
    }
}

main().catch(console.error);
